# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to build a console app; compiles for both Windows (x64) and Linux; copies EXE to storage for downloading ease
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
trigger:
  branches:
    include: 
      - main
  paths:
    include:
      - ConsoleAppProjectFolder
    exclude: 
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.bicep'

pool:
  vmImage: 'windows-latest'

name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)

# ----------------------------------------------------------------------------------------------------
resources:
  repositories:
  - repository: pipelineLibrary # Internal name for this repo, append @thisName to the template path
    type: github
    endpoint: lluppesms   # The name of the service connection in AzDO that has access to the GitHub repo
    name: lluppesms/azdo.pipeline.library # The org/name of the GitHub repo with the pipeline templates

# ----------------------------------------------------------------------------------------------------
stages:
- template: /pipes/console-app-pipe.yml@pipelineLibrary
  parameters:
    variableGroupName: 'MyVariableGroupName'
    environments: ['DEMO']  # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']
