# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "FunctionDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include: 
  #     - '**/*.yml'
  #     - '**/*.yaml'
  #     - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
resources:
  repositories:
  - repository: pipelineLibrary # Internal name for this repo, append @thisName to the template path
    type: github
    endpoint: lluppesms   # The name of the service connection in AzDO that has access to the GitHub repo
    name: lluppesms/azdo.pipeline.library # The org/name of the GitHub repo with the pipeline templates

# ----------------------------------------------------------------------------------------------------
stages:
- template: /pipes/infra-only-pipe.yml@pipelineLibrary
  parameters:
    variableGroupName: 'FunctionDemo'
    environments: ['DEMO']  # ['DEV','PROD'] ['DEV','QA'] or ['DEV','QA','PROD']
